services:
  note-maker-app-project:
    build:
      context: ./note-maker-app-project
      dockerfile: Dockerfile
    ports:
      - "5175:80" # Локальный порт 5175 -> Порт 80 внутри контейнера
    restart: always