services:
  note-maker-app-project:
    build:
      context: ../  # Корневая папка (base)
      dockerfile: ./note-maker-app-project/Dockerfile
    env_file:
      - ../.env  # Указываем путь к .env файлу относительно docker-compose.yml
    ports:
      - "5175:80"
    restart: always

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: always

  telegram-bot:
    build:
      context: ../  # Контекст — это корень проекта (base_dir)
      dockerfile: ./docker/Dockerfile.bot  # Указываем путь до Dockerfile.bot
    env_file:
      - ../.env  # Указываем путь к .env файлу относительно docker-compose.yml
    depends_on:
      - redis
    restart: always

  fastapi:
    build:
      context: ../  # Контекст — это корень проекта (base_dir)
      dockerfile: ./docker/Dockerfile.api  # Указываем путь до Dockerfile.api
    env_file:
      - ../.env  # Указываем путь к .env файлу относительно docker-compose.yml
    ports:
      - "127.0.0.1:8000:8000"  # Проброс порта только на localhost хоста
    depends_on:
      - redis        # FastAPI зависит от Redis
    restart: always