services:
  note-maker-app-project:
    build:
      context: ../note-maker-app-project
      dockerfile: ../note-maker-app-project/Dockerfile
    ports:
      - "5175:80"
    restart: always

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: always

  telegram-bot:
    build:
      context: ../  # Контекст — это корень проекта (base_dir)
      dockerfile: ./docker/Dockerfile.bot  # Указываем путь до Dockerfile.bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - FASTAPI_HOST=${FASTAPI_HOST}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    restart: always